### ISSUE TITLE
"Error: execution timed out" during Quickstart Guide

### ISSUE THREAD

**Issue by mwmattis** [Hirebotics/urscript-tools#34]
Hi.

I tried to run your [Quickstart Guide](https://github.com/Hirebotics/urscript-tools#quick-start) under Linux.
The dependencies like docker, nodejs & npm have been installed successfully.
But when running `sudo npm run intro` I get following error:

```
[...]
Digest: sha256:3a335fd2b7f15dd66a87ab8d57149f226683a5b9e62e4a34ae0c32a5afbcf0d9
Status: Downloaded newer image for hirebotics/ursim:5.8.0
Error: execution timed out
    at Timeout._onTimeout (/home/user/urscript-tools-example/node_modules/@hirebotics/urscript-tools/dist/runner/URScriptExecutor.js:106:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
Can you help me out?

Best regards,
Mattis

**Comment by zachboyd** [comment]
Mattis - Thanks for reaching out. Did you try to the command again and if so did you see the execution timeout each time? Also, which Linux distribution are you running? I will try to replicate on my end.  Thanks!

**Comment by zachboyd** [comment]
@mwmattis - Quick update. On a fresh linux image I was able to replicate the initial `execution timed out` error on the first launch, however upon a subsequent execution it did work successfully (screenshot below). This implies there is an issue our end when launching for the first time where we need to wait longer until the UR controller is ready, but you should be able to wait a small period after the first launch and then run it successfully. Give that a shot and let me know if it works for you. In the meantime, I will see if we can put a permanent solution in place. Thanks again for letting us know! 

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/4779190/107540638-e2862380-6b8b-11eb-8ffb-11147fb22be5.png">

**Comment by mwmattis** [comment]
Hey @zachboyd.
Thank you for quick reply. 
You were right. Running it again solved the timeout issue. Yesterday I had the error multiple times in a row but now it is working.
Thanks again!

**Comment by zachboyd** [comment]
Great! I will keep you updated on when a fix is available for the time out on first launch.
